### ISSUE TITLE
Keyborad backlight doesn't work properly with Linux kernel 6.2 

### ISSUE THREAD

**Issue by jeremie2** [slimbook/keyboard#5]
# Hardware and system

- Slimbook Essential 15
- Ubuntu 22.04
- 6.2.0-26-generic
- Package **slimbookrgbkeyboard** installed from *ppa:slimbook/slimbook*

# Issue

After the latest HWE stack updates, keyboard's backlight stopped working properly.
- If the computer is off and I turn it on, the keyboard has only blue light at maximum power and there is no way to decrease it via [fn]+[-] keyboard shortcut or set different colours.
- There is no backlight after suspend.

(No problem with kernel 5.19)

# Error message while installing  kernel 6.2

```
Configurazione di linux-headers-6.2.0-26-generic (6.2.0-26.26~22.04.1)...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.2.0-26-generic

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=6.2.0-26-generic -C /lib/modules/6.2.0-26-generic/build M=/var/lib/dkms/slimbook_keyboard/0.0/build...(
bad exit status: 2)
Error! Bad return status for module build on kernel: 6.2.0-26-generic (x86_64)
Consult /var/lib/dkms/slimbook_keyboard/0.0/build/make.log for more information.
   ...done.
Configurazione di linux-headers-generic-hwe-22.04 (6.2.0.26.26~22.04.7)...
Configurazione di thermald (2.4.9-1ubuntu0.3)...
Configurazione di linux-modules-extra-6.2.0-26-generic (6.2.0-26.26~22.04.1)...
Configurazione di linux-image-6.2.0-26-generic (6.2.0-26.26~22.04.1)...
I: /boot/vmlinuz is now a symlink to vmlinuz-6.2.0-26-generic
I: /boot/initrd.img is now a symlink to initrd.img-6.2.0-26-generic
Configurazione di linux-image-generic-hwe-22.04 (6.2.0.26.26~22.04.7)...
Configurazione di linux-generic-hwe-22.04 (6.2.0.26.26~22.04.7)...
Elaborazione dei trigger per dbus (1.12.20-2ubuntu4.1)...
Elaborazione dei trigger per man-db (2.10.2-1)...
Elaborazione dei trigger per initramfs-tools (0.140ubuntu13.4)...
update-initramfs: Generating /boot/initrd.img-5.19.0-50-generic
Elaborazione dei trigger per linux-image-6.2.0-26-generic (6.2.0-26.26~22.04.1)...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.2.0-26-generic

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=6.2.0-26-generic -C /lib/modules/6.2.0-26-generic/build M=/var/lib/dkms/slimbook_keyboard/0.0/build...(
bad exit status: 2)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/slimbook-keyboard-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.2.0-26-generic (x86_64)
Consult /var/lib/dkms/slimbook_keyboard/0.0/build/make.log for more information.
   ...done.
```

# Log files

## /var/crash/slimbook-keyboard-dkms.0.crash

```
ProblemType: Package
DKMSBuildLog:
 DKMS make.log for slimbook_keyboard-0.0 for kernel 6.2.0-26-generic (x86_64)
 dom 20 ago 2023, 17:37:32, CEST
 make: ingresso nella directory «/usr/src/linux-headers-6.2.0-26-generic»
 warning: the compiler differs from the one used to build the kernel
   The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
   You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
   CC [M]  /var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.o
 /var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.c:701:27: error: initialization of ‘void (*)(struct acpi_device *)’ from incompatible pointer type ‘int (*)(struct acpi_device *)’ [-Werror=incompatible-pointer-types]
   701 |                 .remove = clevo_acpi_remove,
       |                           ^~~~~~~~~~~~~~~~~
 /var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.c:701:27: note: (near initialization for ‘clevo_acpi_driver.ops.remove’)
 cc1: some warnings being treated as errors
 make[1]: *** [scripts/Makefile.build:260: /var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.o] Errore 1
 make: *** [Makefile:2026: /var/lib/dkms/slimbook_keyboard/0.0/build] Errore 2
 make: uscita dalla directory «/usr/src/linux-headers-6.2.0-26-generic»
DKMSKernelVersion: 6.2.0-26-generic
Date: Sun Aug 20 17:37:34 2023
DuplicateSignature: dkms:slimbook-keyboard-dkms:0.0:/var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.c:701:27: error: initialization of ‘void (*)(struct acpi_device *)’ from incompatible pointer type ‘int (*)(struct acpi_device *)’ [-Werror=incompatible-pointer-types]
Package: slimbook-keyboard-dkms 0.0
PackageVersion: 0.0
SourcePackage: slimbook-keyboard-dkms
Title: slimbook-keyboard-dkms 0.0: slimbook_keyboard kernel module failed to build
```

## /var/lib/dkms/slimbook_keyboard/0.0/build/make.log

```
DKMS make.log for slimbook_keyboard-0.0 for kernel 6.2.0-26-generic (x86_64)
dom 20 ago 2023, 17:37:54, CEST
make: ingresso nella directory «/usr/src/linux-headers-6.2.0-26-generic»
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.o
/var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.c:701:27: error: initialization of ‘void (*)(struct acpi_device *)’ from incompatible pointer type ‘int (*)(struct acpi_device *)’ [-Werror=incompatible-pointer-types]
  701 |                 .remove = clevo_acpi_remove,
      |                           ^~~~~~~~~~~~~~~~~
/var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.c:701:27: note: (near initialization for ‘clevo_acpi_driver.ops.remove’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:260: /var/lib/dkms/slimbook_keyboard/0.0/build/clevo_platform.o] Errore 1
make: *** [Makefile:2026: /var/lib/dkms/slimbook_keyboard/0.0/build] Errore 2
make: uscita dalla directory «/usr/src/linux-headers-6.2.0-26-generic»
```

# Workaround

Back to Linux kernel 5.19

Thanks for any help!

**Comment by Lt-Henry** [comment]
Hi, we have just updated slimbook-keyboard-dkms package to 0.1.1. It should fix your problem with kernel 6.2 (and beyond)

**Comment by jeremie2** [comment]
Thanks for your help.
Unfortunately now I have the same problem with the old kernel too

The good news is that the installation of kernel 6.2 doesn't return any error:
```
 * dkms: running auto installation service for kernel 6.2.0-26-generic
   ...done.
```

So I tried reinstalling the **slimbookrgbkeyboard** package to see if there were any errors and... there might be:
```
Configurazione di slimbook-qc71-dkms (0.2.2)...
Building for 5.19.0-50-generic 6.2.0-26-generic
Building for architecture x86_64
This package appears to be a binaries-only package
 you will not be able to build against kernel 5.19.0-50-generic
 since the package source was not provided
This package appears to be a binaries-only package
 you will not be able to build against kernel 6.2.0-26-generic
 since the package source was not provided
Configurazione di slimbook-keyboard-dkms (0.1.1)...
Building for 5.19.0-50-generic 6.2.0-26-generic
Building for architecture x86_64
This package appears to be a binaries-only package
 you will not be able to build against kernel 5.19.0-50-generic
 since the package source was not provided
This package appears to be a binaries-only package
 you will not be able to build against kernel 6.2.0-26-generic
 since the package source was not provided
Configurazione di slimbookrgbkeyboard (0.3.7beta)...
Running postinst...
ite8291r3-ctl
ite8291r3_driver installed!
Checking devices
device handle could not be acquired: no suitable device found
clevo_platform set to install.
2023-08-25 22:11:54,934 - <module>:116 - INFO - Config check executed as pinguinux
2023-08-25 22:11:54,934 - main:42 - INFO - Checking configuration
2023-08-25 22:11:54,934 - main:50 - INFO - Configuration folder (/home/pinguinux/.config/slimbookrgbkeyboard) found!
2023-08-25 22:11:54,935 - main:53 - DEBUG - uid=1000 file_uid=1000
2023-08-25 22:11:54,935 - check_config_file:71 - INFO - Checking Slimbookrgbkeyboard's Configuration
2023-08-25 22:11:54,935 - check_config_file:81 - INFO - Checking section: CONFIGURATION ...
2023-08-25 22:11:54,936 - check_config_file:101 - INFO - Incidences not found.
Elaborazione dei trigger per desktop-file-utils (0.26-1ubuntu3)...
Elaborazione dei trigger per gnome-menus (3.36.0-1ubuntu3)...
Elaborazione dei trigger per man-db (2.10.2-1)...
Elaborazione dei trigger per mailcap (3.70+nmu1ubuntu1)...
```

I hope this is helpful.
Please let me know if you want me to run any specific commands.

**Comment by Lt-Henry** [comment]
I've already uploaded the fix (I hope so :D ). Launchpad is a bit lazy today so it may take a while to be available.

**Comment by jeremie2** [comment]
It works! :D
Thank you very much for your great help, backlight adjustment is under control again.

Should I close this issue as "completed"?

**Comment by Lt-Henry** [comment]
Thanks to you for taking the time describing the problem and providing logs. It helped me to track a similar problem with another dkms package.

> Should I close this issue as "completed"?

Don't worry, I'll do it.
